### ISSUE TITLE
Error with vite 2.7.10

### ISSUE THREAD

**Issue by mariusheine** [geprog/vite-plugin-env-config#16]
It seems like there is an error with vite v2.7.10

```
[vite-plugin-env-config] ENOENT: no such file or directory, open '.../dist/env-config.template.js'
... build: error during build:
... build: Error: ENOENT: no such file or directory, open '.../dist/env-config.template.js'
... build:     at Object.openSync (fs.js:498:3)
... build:     at Object.writeFileSync (fs.js:1524:35)
... build:     at Object.closeBundle (.../node_modules/.pnpm/@geprog+vite-plugin-env-config@4.0.0_vite@2.7.10/node_modules/@geprog/vite-plugin-env-config/dist/index.js:74:25)
```

If moving to vite v2.7.13 the error is resolved.

**Comment by mariusheine** [comment]
I found out the issue. It happens when the dist folder is not existing yet, because `writeFileSync` does not check this. So with making a simple `mkdirSync` before it seems to fix it.
